import { Header } from "../../components/Header/Header";
import { Footer } from "../../components/Footer/Footer";
import "../../styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: "noindex, nofollow",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <main>
          <Header></Header>
          {children}
          <Footer></Footer>
        </main>
      </body>
    </html>
  );
}
